spring:
  jpa:
    generate-ddl: 'false'
    database: mysql
    defer-datasource-initialization: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
  thymeleaf:
    cache: false
  datasource:
    url: ENC(TagPEsjqJt4ySoDvM1hJWbmbrM4/rsOC9Vg3sGED9TvqsoGbNcyQxhMQXYAvdiQWP5ffyxjrtxribYaUclZNRmYZ0FZku1Tm8xJHnXjDlRHlv7Hpy3eqdqmgNv8ZuijQ)
    password: ENC(wTTncixr5KBfMMdW4lTEVBC9JJk1+bcN)
    username: ENC(ItHQiVe7HNltWJbKPPciFQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB
logging:
  config: classpath:logback.xml
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
#jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
secret-key-source: ${SECRET_KEY_SOURCE}
#s3
cloud:
  aws:
    s3:
      bucket: ENC(4q27BRSdpVCjB4RGlDPisohwY8POoqwX)
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ENC(2ZAyIpTDzAmMhq59ZabZctFKhCcuWSaUpyLsUA/8z8c=)
      secretKey: ENC(RwmAKGYQSvwVaxY1MmSHuAyW5wLWc2Wwor/u1m7V/gojv5G1f7ntAYGe8jHStSqGb/M+5tSkLrE=)

#kakaoLogin
kakao:
  kakaoClientId: ENC(KEuX4dxmnX4zNf2DaN/7AScvH265DnE5EUBmFf2edAScwbIwccemuPNj/Iew497p)